variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
    paths:
    - "$CI_PROJECT_DIR/pip-cache"

test:
    image: python:3.6

    script:
    - pip install -r requirements.txt
    - cp default_config.py config.py
    - coverage run --source=./app/service -m unittest discover -vs test/
    - coverage report -m
