variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"
  BRANCH_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  RELEASE_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH:latest

services:
  - docker:dind

image: gitlab/dind

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"

stages:
  - build
  - test
  - release

build:
  stage: build

  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker pull $BRANCH_IMAGE || true
    - docker build --cache-from $BRANCH_IMAGE -t $BRANCH_IMAGE -f docker/Dockerfile .
    - docker push $BRANCH_IMAGE
  tags:
    - docker

unittest:
  image: $BRANCH_IMAGE
  stage: test

  script:
  - coverage run --source=./app/service -m unittest discover -vs test/
  - coverage report -m
  - coverage html
  artifacts:
    paths:
    - htmlcov/
    expire_in: 1 week

flake8:
  image: $BRANCH_IMAGE
  stage: test
  script:
   - flake8 ./app

miscellaneous:
  image: $BRANCH_IMAGE
  stage: test
  script:
   - "[ -z $(grep -R fuzzy app/translations/) ]"
   - "[ $(python manage.py db heads 2>/dev/null | grep head | wc -l) -lt 2 ]"

release:
  script:
    - docker pull $BRANCH_IMAGE
    - docker tag $BRANCH_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
  tags:
    - docker
