version: "2"
services:
  app:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - database
    volumes:
      - .:/app
      - /tmp/viaduct-master:/tmp/viaduct-master
    command: "sh docker-entrypoint.sh"

  database:
    image: postgres:10-alpine
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: viaduct
      POSTGRES_DB: viaduct

  adminer:
    image: dehy/adminer
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"