version: "3.4"
services:
  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - database

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: viaduct
      POSTGRES_DB: viaduct
