
swagger: '2.0'
info:
  version: 1.0.0
  title: Study Association via
  description: The public API of the study association via of the University of Amsterdam
  license:
    name: MIT
  contact:
    name: ICT committee
    url: https://svia.nl
    email: ict@svia.nl

basePath: "/api/pimpy"
schemes:
  - "https"
produces:
  - application/json
consumes:
  - application/json

tags:
  - name: tasks
    description: Operations related to pimpy tasks.
  - name: minutes
    description: Operations related to pimpy minutes.

paths:
  /tasks/:
    get:
      summary: List all tasks for the current user.
      parameters:
        - name: groupId
          in: query
          type: integer
          description: Filter by a groupId
      responses:
        200:
          description: Successfull response
          schema:
            $ref: '#/definitions/PimpyTaskList'
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/ResourceNotFound'
        500:
          $ref: '#/responses/InternalServerError'

      security:
        - OAuth2Implicit: [pimpy_read]
      tags:
       - tasks

    post:
      summary: Create a new task.
      parameters:
        - name: task
          in: body
          required: true
          description: task
          schema:
            $ref: '#/definitions/PimpyTask'
      responses:
        201:
          description: Successfull create
          schema:
            $ref: '#definitions/PimpyTask'
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        409:
          $ref: '#/responses/Conflict'
        500:
          $ref: '#/responses/InternalServerError'
      security:
        - OAuth2Implicit: [pimpy_write]
      tags:
        - tasks

  /tasks/{taskId}/:
    get:
      summary: Retrieve a task
      parameters:
        - name: taskId
          in: path
          type: integer
          required: true
      responses:
        200:
          description: The requested task
          schema:
            $ref: '#/definitions/PimpyTask'
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/ResourceNotFound'
        500:
          $ref: '#/responses/InternalServerError'
      security:
        - OAuth2Implicit: [pimpy_read]
      tags:
        - tasks
    put:
      summary: Put a new version of the task
      parameters:
        - name: taskId
          in: path
          type: integer
          required: true
        - name: task
          in: body
          schema:
            $ref: '#/definitions/PimpyTask'
      responses:
        204:
          description: Updated, no response
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/ResourceNotFound'
        500:
          $ref: '#/responses/InternalServerError'
      security:
        - OAuth2Implicit: [pimpy_write]
      tags:
        - tasks

  /minutes/:
    get:
      summary: List all minutes for the current user.
      parameters:
        - name: groupId
          in: query
          type: integer
          description: Filter by a groupId
      responses:
        200:
          description: Successfull response
          schema:
            $ref: '#/definitions/PimpyMinuteList'
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/ResourceNotFound'
        500:
          $ref: '#/responses/InternalServerError'
      security:
        - OAuth2Implicit: [pimpy_read]
      tags:
       - minutes

    post:
      summary: Create a new minute.
      parameters:
        - name: task
          in: body
          required: true
          description: task
          schema:
            $ref: '#/definitions/PimpyMinute'
      responses:
        201:
          description: Successfull create
          schema:
            $ref: '#definitions/PimpyMinute'
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        409:
          $ref: '#/responses/Conflict'
        500:
          $ref: '#/responses/InternalServerError'
      security:
        - OAuth2Implicit: [pimpy_write]
      tags:
        - minutes

  /minutes/{minuteId}/:
    get:
      summary: Retrieve a minute
      parameters:
        - name: minuteId
          in: path
          type: integer
          required: true
      responses:
        204:
          description: Updated, no response
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/ResourceNotFound'
        500:
          $ref: '#/responses/InternalServerError'
      security:
        - OAuth2Implicit: [pimpy_read]
      tags:
        - minutes

    put:
      summary: Put a new version of the minute
      parameters:
        - name: minuteId
          in: path
          type: integer
          required: true
        - name: minute
          in: body
          schema:
            $ref: '#/definitions/PimpyMinute'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/PimpyMinute'
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/ResourceNotFound'
        500:
          $ref: '#/responses/InternalServerError'
      security:
        - OAuth2Implicit: [pimpy_write]
      tags:
        - minutes


responses:
  ResourceNotFound:
    description: Referenced resource could not be found.
    schema:
      $ref: '#/definitions/Error'
  Unauthorized:
    description: You are not authenticated. Please authenticate and try again.
    schema:
      $ref: '#/definitions/Error'
  Forbidden:
    description: You have no permission to access the specified resource.
    schema:
      $ref: '#/definitions/Error'
  ValidationError:
    description: The supplied object is invalid. Error detail will contain the validation error.
    schema:
      $ref: '#/definitions/Error'
  NotAcceptableError:
    description: The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.
    schema:
      $ref: '#/definitions/Error'
  UnsupportedMediaType:
    description: The requested resource does not understand the media type sent in the request.
    schema:
      $ref: '#/definitions/Error'
  Conflict:
    description: There was a conflict while trying to perform your request. Error detail will contain the detailed conflict.
    schema:
      $ref: '#/definitions/Error'
  InternalServerError:
    description: Something went wrong in the server. Please try again.
    schema:
      $ref: '#/definitions/Error'


definitions:
  PimpyTaskStatus:
    type: string
    enum:
      - new
      - started
      - done      # Marked done by user
      - remove    # Marked for removal by user
      - finished  # DONE in minute
      - deleted   # REMOVE in minute

  PimpyTaskBase:
    required:
      - groupId
      - title
      - status
    properties:
      title:
        type: string
      groupId:
        type: integer
      taskId:
        type: integer
        description: Unique identifier used in request paths.
        readOnly: true
      status:
        $ref: '#/definitions/PimpyTaskStatus'

  PimpyTask:
    allOf:
      - $ref: '#/definitions/PimpyTaskBase'
      - type: object
        required:
          - userIds
        properties:
          userIds:
            type: array
            items:
              type: integer
          content:
            type: string
          minuteId:
            type: integer
          line:
            type: integer
            description: line of the minute the task was defined on.
          taskB32Id:
            type: string
            description: Base 32 encoded unique identifier, used to display to end user.
            readOnly: true

  PimpyTaskList:
    type: array
    items:
      $ref: "#/definitions/PimpyTaskBase"

  PimpyMinuteMinimal:
    type: object
    required:
      - groupId
      - minuteDate
    properties:
      groupId:
        type: integer
      minuteDate:
        type: string
        format: date
      minuteId:
        type: integer
        description: Unique identifier used in request paths.
        readOnly: true

  PimpyMinute:
    allOf:
    - $ref: "#/definitions/PimpyMinuteMinimal"
    - type: object
      required:
        - content
      properties:
        content:
          type: string

  PimpyMinuteList:
    type: array
    items:
      $ref: "#/definitions/PimpyMinuteMinimal"

  Error:
    type: object
    description: Generic error response, modelled after RFC 7807.
    properties:
      code:
        type: integer
        description: Error code within the system.
      title:
        type: string
        description: This title is not meant to be shown to users. Please use the code to parse the error.
      detail:
        type: string
        description: Error details, to help developers detect what went wrong.
      type:
       type: string
       description: Link to additional documentation regarding the error.



securityDefinitions:
  OAuth2Implicit:
    type: oauth2
    description: >-
      The API uses OAuth2 to grant access, for more information see the
      explicit documentation [here](https://svia.nl/oauth2/)
    flow: implicit
    authorizationUrl: "/oauth/authorize"
    x-tokenInfoFunc: "app.views.oauth.token_info"
    scopes:
      pimpy_read: "Read access to your Pimpy data"
      pimpy_write: "Write access to your Pimpy data"
# vim: sw=2 ts=2