{% from 'swagger/macros.yaml' import security, error_definition, responses %}
swagger: '2.0'
info:
  version: 1.0.0
  title: Study Association via
  description: The public API of the study association via of the University of Amsterdam
  license:
    name: MIT
  contact:
    name: ICT committee
    url: https://svia.nl
    email: ict@svia.nl

basePath: "/api/token/"
schemes:
  - "{{protocol}}"
produces:
  - application/json
consumes:
  - application/json

tags:
  - name: token
    description: Token related operations.

paths:
  /info/:
    get:
      summary: Get information of the token used in the request.
      responses:
        200:
          description: Successfull response
          schema:
            $ref: '#/definitions/TokenInfo'
        400:
          $ref: '#/responses/ValidationError'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/ResourceNotFound'
        500:
          $ref: '#/responses/InternalServerError'
      security:
        - OAuth2Implicit: []
      tags:
       - token

{{ responses() }}

definitions:
  TokenInfo:
    type: object
    required:
      - active
      - client_id
      - expires
      - first_name
      - last_name
      - scope
    properties:
      active:
        type: string
        enum:
          - "true"
      client_id:
        type: string
      expires:
        type: string
        format: date-time
      first_name:
        type: string
      last_name:
        type: string
      scope:
        type: array
        items:
          type: string
{{ error_definition() }}

{{ security() }}
# vim: sw=2 ts=2